parameters:
    # Adds a fallback DATABASE_URL if the env var is not set. This allows you
    # to run cache:warmup even if your environment variables are not available
    # yet. You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        driver: 'pdo_sqlite'
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: '3.15'
        charset: utf8mb4

        types:
            uuid: Acme\App\Infrastructure\Persistence\Doctrine\Type\UuidType
            binary_uuid: Acme\App\Infrastructure\Persistence\Doctrine\Type\BinaryUuidType
            user_id: Acme\App\Infrastructure\Persistence\Doctrine\Type\UserIdType
            message_id: Acme\App\Infrastructure\Persistence\Doctrine\Type\MessageIdType
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        mappings:
            # Each mapping must have its own 'dir' directive.
            # If we put them all in the same dir, they will not be found.
            Acme\App\Core\Component\Message\Domain\Message:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/doctrine/message'
                prefix: 'Acme\App\Core\Component\Message\Domain\Message'
                alias: Message
            Acme\App\Core\Component\User\Domain\User:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/doctrine/user'
                prefix: 'Acme\App\Core\Component\User\Domain\User'
                alias: User
        dql:
            string_functions:
                group_concat: DoctrineExtensions\Query\Mysql\GroupConcat
