doctrine_migrations:
    dir_name: '%kernel.project_dir%/build/Migration/Version'
    # namespace is arbitrary but should NOT be autoloaded in production
    namespace: Acme\App\Build\Migration\Version
