twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - '@Web/Core/Port/Form/layout.html.twig'
        - '@Web/Core/Port/Form/fields.html.twig'
    paths:
        '%kernel.project_dir%/src/Core': Core # this is so twig can find the email templates
        # this is where the base email templates live:
        '%kernel.project_dir%/src/Core/SharedKernel/Port/Notification/Client/Email/Template': SharedKernel
        '%kernel.project_dir%/src/Infrastructure/TemplateEngine': TemplateEngine
