monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: main_nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        main_nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        stdout: # So docker receives the logs as well
            type: fingers_crossed
            action_level: error
            handler: stdout_nested
            excluded_http_codes: [ 404, 405 ]
        stdout_nested:
            type: stream
            path: 'php://stdout'
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
