parameters:
    # SMS settings
    sms.default_destination: '+19009990006' # Can be a developer phone number, but usually shouldn't
    sms.twilio.client.sid: 'some-dummy-DEV-id'
    sms.twilio.client.token: 'some-dummy-DEV-token'

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false
#        # defines the scalar arguments once and apply them to any service defined/created in this file
#        bind:
#            $defaultDestination: '%sms.default_destination%'

    # So we can use these fixtures
    Acme\App\Test\Fixture\Doctrine\:
        resource: '../tests/Fixture/Doctrine/*'
